[package]
name = "mu_ui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy = { workspace = true }
camino.workspace = true
mu_core = { path = "../mu_core" }
mu_assets = { path = "../mu_assets" }
mu_editor_admin = { path = "../mu_editor_admin" }
mu_gameplay = { path = "../mu_gameplay" }
