pub mod character;
pub mod chat;
pub mod codec;
pub mod combat;
pub mod connect;
pub mod connect_server;
pub mod error;
pub mod frame;
pub mod items;
pub mod login;
pub mod movement;
pub mod pets;
pub mod player_shop;
pub mod session;
pub mod skills;
pub mod trade;
pub mod vault;
pub mod wire;
pub mod world;

pub const CRATE_NAME: &str = env!("CARGO_PKG_NAME");

pub use codec::{decode_packet, encode_packet};
pub use connect::ServerEntry;
pub use error::PacketCodecError;
pub use frame::PacketFrame;
pub use items::{ChaosMachineMixType, FruitUsage, ItemStorageKind};
pub use pets::{PetCommandMode, PetType, StorageType};
pub use skills::SkillIndex;
pub use trade::TradeButtonState;
pub use vault::VaultMoneyMoveDirection;
